stages:
  # - dist
  - DeployDev

DeployDev:
  stage: DeployDev
  image: node:18.16.0-buster-slim
  only: ['develop']
  script:
    - apt-get update && apt-get install rsync -y && apt-get install openssh-server -y
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$IP_TEST_SERVER" >> ~/.ssh/known_hosts
    - echo "$SSH_KEY_DEV" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - echo "$ENV_DEV" > .env
    - rsync --progress -avzh -e "ssh " --rsync-path="sudo rsync" --exclude='.git' .  ubuntu@$IP_TEST_SERVER:~/vexere
    - ssh ubuntu@$IP_TEST_SERVER "cd vexere && yarn && yarn build && pm2 delete vexere && pm2 start --name "vexere" --force npm -- start"

#or deploy with docker